* Keymaps
* Config edit/reload
** Edit
    #+begin_src emacs-lisp
      (defun config-visit ()
	(interactive)
	(find-file "~/.emacs.d/config.org"))
      (global-set-key (kbd "C-c e") 'config-visit)
    #+end_src
** Reload
    #+begin_src emacs-lisp
      (defun config-reload ()
	(interactive)
	(org-babel-load-file (expand-file-name "~/.emacs.d/config.org")))
      (global-set-key (kbd "C-c r") 'config-reload)
    #+end_src
* Org
** Open source editing in its own window
    #+begin_src emacs-lisp
      (setq org-src-window-setup 'current-window)
    #+end_src
** Emacs Lisp template
    #+begin_src emacs-lisp
      (add-to-list 'org-structure-template-alist
		   '("el" . "src emacs-lisp"))
    #+end_src
* QoL
** GUI elements disabled
    #+begin_src emacs-lisp
      (tool-bar-mode -1)
      (menu-bar-mode -1)
      (scroll-bar-mode -1)
    #+end_src
** Line number enabled
    #+begin_src emacs-lisp
      (add-hook 'prog-mode-hook 'display-line-numbers-mode)
      (add-hook 'text-mode-hook 'display-line-numbers-mode)
    #+end_src
** Enable omni-directional copypasting
    #+begin_src emacs-lisp
      (setq x-select-enable-clipboard t)
    #+end_src
** Show parent parentheses
    #+begin_src emacs-lisp
      (show-paren-mode 1)
    #+end_src
** Scroll conservatively
    #+begin_src emacs-lisp
      (when window-system (setq scroll-conservatively 100))
    #+end_src
** Disable default startup screen
    #+begin_src emacs-lisp
      (setq inhibit-startup-message t)
    #+end_src
** Disable ring bell
    #+begin_src emacs-lisp 
      (setq ring-bell-function 'ignore)
    #+end_src
** Disable auto save/backup
    #+begin_src emacs-lisp
      (setq make-backup-files nil
	    auto-save-default nil)
    #+end_src
** Map yes/no to y/n
    #+begin_src emacs-lisp
      (defalias 'yes-or-no-p 'y-or-n-p)
    #+end_src
** Move between subwords
    #+begin_src emacs-lisp
      (global-subword-mode 1)
    #+end_src
** Autocomplete parentheses
    #+begin_src emacs-lisp
      (setq electric-pair-pairs '(
				  (?\( . ?\))
				  (?\[ . ?\])
				  (?\{ . ?\})
				  (?\" . ?\")
				  ))
      (electric-pair-mode t)
    #+end_src
** Delete whole word
    # #+begin_src emacs-lisp
    #   (defun kill-whole-word ()
    # 	(interactive)
    # 	(backward-word)
    # 	(kill-word 1))
    #   (define-key 'string-manipulation (kbd "d") 'kill-whole-word)
    # #+end_src
** Show line and column number on modeline
    #+begin_src emacs-lisp
      (line-number-mode 1)
      (column-number-mode 1)
    #+end_src
** Easy window resize
Default keybind is Super-Control-<arrow>
    #+begin_src emacs-lisp
      (global-set-key (kbd "s-C-<left>") 'shrink-window-horizontally)
      (global-set-key (kbd "s-C-<right>") 'enlarge-window-horizontally)
      (global-set-key (kbd "s-C-<down>") 'shrink-window)
      (global-set-key (kbd "s-C-<up>") 'enlarge-window)
    #+end_src
** Kill all buffers except current buffer
    #+begin_src emacs-lisp
      (defun kill-other-buffers ()
	"Kill all other buffers."
	(interactive)
	(mapc 'kill-buffer (delq (current-buffer) (buffer-list))))
      (global-set-key (kbd "C-c k") 'kill-other-buffers)
    #+end_src
** Defer loading packages for faster startup time
    #+begin_src emacs-lisp
      (setq use-package-always-defer t)
    #+end_src
** Visual line mode enabled for all buffers
Text will be put on a new line when it hits the border of buffer.
Feel free to disable this for some buffers (e.g email buffer).
    #+begin_src emacs-lisp
      (global-visual-line-mode t)
    #+end_src
** Scroll buffer without moving point (at least until point hits up or bottom buffer's border)
CUA mode is enabled and fortunately it has this built in so we will use it.
    #+begin_src emacs-lisp
      (global-set-key (kbd "M-n") (lambda () (interactive) (cua-scroll-up 1)))
      (global-set-key (kbd "M-p") (lambda () (interactive) (cua-scroll-down 1)))
    #+end_src
* Terminal
** Setting default shell to bash
Enable terminal emulator (*ansi-term* by default) to use bash without confirming.
   #+begin_src emacs-lisp
     (defvar my-term-shell "/bin/bash")
     (defadvice ansi-term (before force-bash)
       (interactive (list my-term-shell)))
     (ad-activate 'ansi-term)
   #+end_src
** Bind Super-Return to open terminal 
    #+begin_src emacs-lisp
      (global-set-key (kbd "<s-return>") 'ansi-term)
    #+end_src
* diminish
    #+begin_src emacs-lisp
      (use-package diminish
	:ensure t)
    #+end_src
* which-key
    #+begin_src emacs-lisp
      (use-package which-key
	:ensure t
	:init
	(which-key-mode)
	:diminish which-key-mode)
    #+end_src
* IDO
** Enable IDO mode
    #+begin_src emacs-lisp
      (setq ido-enable-flex-matching nil)
      (setq ido-create-new-buffer 'always)
      (setq ido-everywhere t)
      (ido-mode 1)
    #+end_src
** IDO-vertical
    #+begin_src emacs-lisp
      (use-package ido-vertical-mode
	:ensure t
	:init
	(ido-vertical-mode 1))
      (setq ido-vertical-define-keys 'C-n-C-p-up-down-left-right)
    #+end_src
* smex  
Better Meta-x interface.
    #+begin_src emacs-lisp
      (use-package smex
	:ensure t
	:init (smex-initialize)
	:bind
	("M-x" . smex))
    #+end_src
* ibuffer
Better buffer menu. Default keybind is still C-x C-b.
   #+begin_src emacs-lisp
     (global-set-key (kbd "C-x C-b") 'ibuffer)
   #+end_src
* avy
** Description
Come with many useful functionalities concerning text utilities.
** Jump to character
Jump to character quickly. Default keybind is Meta-s.
    #+begin_src emacs-lisp
      (use-package avy
	:ensure t
	:bind
	("M-s" . avy-goto-char))
    #+end_src
** Copy and yank whole line to the line above cursor's current line
# *** Code
#     #+begin_src emacs-lisp
#       (define-key string-manipulation (kbd "c") 'avy-copy-line)
#     #+end_src
* swiper
Create a nice looking mini-buffer that you can traverse with C-n, C-p whenever you search for word.
    #+begin_src emacs-lisp
      (use-package swiper
	     :ensure t
	     :bind ("C-s" . 'swiper)
	     ("C-r" . 'swiper))
      ;; Force swiper to scan actual lines only even if visual line is enabled.
      (setq swiper-use-visual-line nil)
      (setq swiper-use-visual-line-p (lambda (a) nil))
    #+end_src
* rainbow
** Display hex code color
Display color of hex code in its background.
    #+begin_src emacs-lisp
      (define-globalized-minor-mode global-rainbow-mode rainbow-mode 
	(lambda () (rainbow-mode 1)))
      (global-rainbow-mode 1)
    #+end_src
** Color parentheses
    #+begin_src emacs-lisp
      (use-package rainbow-delimiters
	:ensure t
	:init
	(add-hook 'prog-mode-hook #'rainbow-delimiters-mode)
	:diminish rainbow-mode)
    #+end_src
* ace-window
Switch windows quickly. Default keybind is Meta-o
    #+begin_src emacs-lisp
      (use-package ace-window
	:ensure t
	:bind
	("M-o" . ace-window))
    #+end_src
* sudo-edit
Edit in super user mode.
    #+begin_src emacs-lisp
      (use-package sudo-edit
	:ensure t
	:bind ("s-e" . sudo-edit))
    #+end_src
* smart-hungry-delete
Delete all white spaces till the first non white space character is found.
    #+begin_src emacs-lisp
      (use-package smart-hungry-delete
	:ensure t
	:bind (("<backspace>" . smart-hungry-delete-backward-char)
	       ("C-d" . smart-hungry-delete-forward-char)))
    #+end_src
* cua-mode
    #+begin_src emacs-lisp
      (use-package cua-base
	:init (cua-mode t))
    #+end_src
* dashboard
Startup screen, where Seiga shows up.
    #+begin_src emacs-lisp
      (use-package dashboard
	:ensure t
	:defer nil
	:config
	(dashboard-setup-startup-hook)
	(setq dashboard-items '((recents . 10)))
	(setq dashboard-banner-logo-title "T A O M A C S - The abominable Emacs distribution!")
	(setq dashboard-startup-banner "~/.emacs.d/seigasama.png")
	(setq dashboard-center-content t)
	(setq dashboard-show-shortcuts nil)
	(setq dashboard-set-init-info t)
	(setq dashboard-init-info (format "%d packages loaded in %s"
					  (length package-activated-list) (emacs-init-time)))
	(setq dashboard-set-footer nil)
	(setq dashboard-set-navigator nil))
    #+end_src
* dired-sidebar
    #+begin_src emacs-lisp
      (use-package dired-sidebar
	:bind (("C-x C-n" . dired-sidebar-toggle-sidebar))
	:ensure t
	:commands (dired-sidebar-toggle-sidebar)
	:init
	(add-hook 'dired-sidebar-mode-hook
		  (lambda ()
		    (unless (file-remote-p default-directory)
		      (auto-revert-mode))))
	:config
	(push 'toggle-window-split dired-sidebar-toggle-hidden-commands)
	(push 'rotate-windows dired-sidebar-toggle-hidden-commands)

	(setq dired-sidebar-subtree-line-prefix "__")
	;; (setq dired-sidebar-theme 'vscode)
	(setq dired-sidebar-use-term-integration t)
	(setq dired-sidebar-use-custom-font t))
    #+end_src
* Magit
    #+begin_src emacs-lisp
      (use-package magit
	:ensure t)
    #+end_src
* eglot
    #+begin_src emacs-lisp
      (use-package eglot
	:ensure t)
    #+end_src
* go-mode
    #+begin_src emacs-lisp
      (use-package go-mode
	:ensure t)
      (add-to-list 'exec-path (expand-file-name "~/go/bin")) 
    #+end_src
* company
    #+begin_src emacs-lisp
      (use-package company
	:ensure t
	:init
	(add-hook 'after-init-hook 'global-company-mode)
	:diminish company-mode)
    #+end_src
* flycheck
    #+begin_src emacs-lisp
      (use-package flycheck
	:ensure t
	:init
	(add-hook 'after-init-hook #'global-flycheck-mode)
	(add-hook 'eglot--managed-mode-hook (lambda () (flymake-mode -1)))
	:bind
	("C-c l" . 'flycheck-list-errors)
	:diminish flycheck-mode)
      (with-eval-after-load 'flycheck
	(setq-default flycheck-disabled-checkers '(emacs-lisp-checkdoc)))
    #+end_src
* Modeline
** powerline
    #+begin_src emacs-lisp
      (use-package powerline
	:ensure t
	:init
	(powerline-default-theme))
    #+end_src
* Diminish built-in minor modes
  #+begin_src emacs-lisp
    (use-package page-break-lines
      :ensure t
      :diminish (page-break-lines-mode visual-line-mode))
    (use-package subword
      :diminish subword-mode)
    (use-package eldoc
      :diminish eldoc-mode)
    (use-package autorevert
      :diminish auto-revert-mode)
  #+end_src
